spring:
  config:
    activate:
      on-profile: dev
    import: application-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE.ENDPOINT_URL}:3306/${DATABASE.NAME}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS.host}
      port: 6379
jwt:
  secret : ${JWT.SECRET}
KAKAO:
  clientId: ${SOCIAL.KAKAO.clientId}
GOOGLE:
  clientId: ${SOCIAL.GOOGLE.clientId}
  clientSecret: ${SOCIAL.GOOGLE.clientSecret}